### ISSUE TITLE
Fix support for non-managed commercetools stores

### ISSUE THREAD

**Issue by tleguijt** [labd/mach-composer#193]
Since version 2.0 support for non-managed commercetools store definitions seems to be broken:
https://docs.machcomposer.io/topics/integrations/commercetools.html#outside-mach-configuration

Example config;

```yaml
stores:
  - key: eu-store
    managed: false
  - key: us-store
    managed: false
```

But following appears in the generated terraform file, while they shouldn't;

```hcl
resource "commercetools_store" "eu-store" {
  key  = "eu-store"
  name = {}
}

resource "commercetools_store" "us-store" {
  key  = "us-store"
  name = {}
}
```
