### ISSUE TITLE
issue when using multipe aws components where one doesn't have endpoints

### ISSUE THREAD

**Issue by bluedread** [labd/mach-composer#221]
### Is your proposal related to a problem?

We had a config with multiple AWS site components. One of those doesn't use `endpoints`: 
```
sites:
  - identifier: tst-aap
    endpoints:
      internal:
        url: some.url
        ...
      external:
        url: another.url
        aws:
          ...
  - identifier: tst-noot
    aws:
      ...
```
There were componentes deployed to the `tst-aap` site that used endpoints, and components to `tst-noot` that didn't use endpoints. When deploying with mach composer version 2.2 this worked. 

When switching to 2.8 this generated an error: 

```
| Error: An error occured:
|
| failed to render resources: plugin aws failed to render resources: aws component requires undeclared endpoint: internal
```

### Describe the solution you'd like

It should be possible to deploy components that don't require an endpoint to a site that doesn't use those, while keeping different aws sites in the same configuration yaml file.

### Describe alternatives you've considered

We've split up the configuration into multiple files, this unblocked us.

### Additional context

-
